# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright Â© 2017-2018 ANSSI. All rights reserved.

# CLIP OS SDK recipe file

features = [ "sdk" ]

[runtime]
additional_capabilities = []

additional_device_bindings = [
    # expose /dev/kvm within SDKs for use by libguestfs:
    "/dev/kvm",
]

cwd = "{{repo}}/products/{{product}}/{{recipe}}/scripts"

prelude_commands = [ ]

postlude_commands = [ ]

writable_assets_dirs_at_build = [ ]

[bootstrap]
rootfs_archive = "{{repo}}/assets/debian/rootfs-2018-07-27.tar.xz"
steps = [
    # Download the source code for all binary packages included in the rootfs:
    "{{repo}}/products/{{product}}/{{recipe}}/scripts/bootstrap.sh",
]

[run]
steps = [
    "bash -li",
]

# vim: set ts=4 sts=4 sw=4 et ft=toml:
